# Site Settings
title: "Avyan Gupta Portfolio"
description: "Electrical & Software Engineering Portfolio"
url: "https://coolavy.github.io"

# Theme Configuration
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark"

# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

# Defaults for pages
# Defaults for pages
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true
      sidebar:
        nav: "docs"
