# Site Settings
title: "Portfolio"
name: "Avyan Gupta"
description: "Hardware & Software Engineering Portfolio"
url: "https://coolavy.github.io"

# Theme Configuration
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark" # Theme skin. Options: dark, contrast, aqua, neon

# Plugins required by the theme
plugins:
  - jekyll-include-cache

# Defaults for pages
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true # Shows a professional profile sidebar on the left
      sidebar:
        nav: "docs"
